language: php

php:
  - 7.0.8

before_install:
  - composer self-update
  
install:
  - cd web
  - composer install
  - composer update
  - cd core
  - composer update
  - ../vendor/bin/phpunit --testsuite=unit 

notifications:
  email: false
  slack: ldso-italien:Q0U7sHHaNrawf6UVsV2J58A9

branches:
  only:
  - master
